// <auto-generated />
using System;
using ChimeWebApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChimeWebApi.Migrations
{
    [DbContext(typeof(IdentityDatabase))]
    partial class IdentityDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ChimeWebApi.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RefreshTokenExpireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("062ea2e0-c625-4d3b-8863-b5bed87244cd"),
                            FirstName = "Anton Jay",
                            LastName = "Cañete",
                            MiddleName = "Adlit",
                            PasswordHash = "AQAAAAIAAYagAAAAEMCAqFd1gUqBRssags1TTRQ82pY9RdgqkwFXMMveYGDymbbWjUBA5RoRZZKBQfm1tw==",
                            RefreshToken = "",
                            RefreshTokenExpireDate = new DateTime(2025, 10, 12, 4, 57, 50, 0, DateTimeKind.Unspecified),
                            Role = "User",
                            UserName = "antonjay23"
                        },
                        new
                        {
                            Id = new Guid("6fda04f9-18a4-475f-80c4-3863e691cc7b"),
                            FirstName = "Angel",
                            LastName = "Pacaña",
                            MiddleName = "Caballes",
                            PasswordHash = "AQAAAAIAAYagAAAAEDOJTHYMo3ZEGpRlyY/ygV8n2gv1zd0sALftHy+bnM9pZe5cdXOwZtijzcLZRZpw8Q==",
                            RefreshToken = "",
                            RefreshTokenExpireDate = new DateTime(2025, 10, 12, 4, 57, 50, 0, DateTimeKind.Unspecified),
                            Role = "User",
                            UserName = "angel26"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
